-- The chest becomes a two-step commit and reveal.
--
-- WHAT CHANGES, AND WHY IT IS STRONGER
-- The previous scheme already committed the server seed before the member
-- could act on it, which is the half most implementations skip. What it did
-- not do was reveal. A seed was published only when the member chose to rotate
-- it, so a member who never rotated could never actually check a single one of
-- their openings. A proof nobody can run is a promise, not a proof.
--
-- So an opening now consumes its commitment. One transaction: the committed
-- seed is revealed and retired, a fresh seed is committed for the next open,
-- the entitlement is spent, the opening is recorded with the revealed seed
-- beside the hash that was published before it, and the cards land in the
-- holdings ledger. The member walks away holding everything needed to rerun
-- the roll, plus the commitment for the chest after this one.
--
-- The order of the two steps is the whole point:
--   1. The realm publishes sha256(seed). The member has it BEFORE they choose
--      anything, so the realm cannot pick a seed to suit what they choose.
--   2. The member fixes their client seed, having seen the hash. The realm
--      cannot know it in advance, so it cannot pick a seed to suit that.
--   3. The open reveals the seed and rolls. Both halves were locked in before
--      either side could see the other's, which is what makes the result
--      neither party's to choose.
--
-- WHY EDITING THE CLIENT SEED IS SAFE, corrected from the previous migration.
-- That one claimed a client seed changed under a live commitment would let a
-- member re-roll a chest they had already seen. That was wrong: a member can
-- never see a roll without consuming an entitlement, and the entitlement is
-- consumed in the same transaction that reveals the seed. Editing the client
-- seed before an open only re-randomises a function whose key they do not
-- know. So the client seed is now editable on the live commitment, which is
-- what makes step 2 above possible at all.

-- The retire-and-recommit pair, folded into the opening so it cannot happen
-- halfway. Replaces the six-argument version from 20260813120000, which is
-- dropped rather than overloaded: two functions named chest_open, one of which
-- forgets to rotate the seed, is precisely the kind of pair where the wrong one
-- gets called for a year.
drop function if exists public.chest_open(uuid, uuid, text, text, jsonb, jsonb);

create or replace function public.chest_open(
  p_profile_id uuid,
  p_entitlement_id uuid,
  -- The commitment being spent. Guarded on still being active, so two opens
  -- racing on one commitment cannot both reveal it.
  p_seed_id uuid,
  p_server_seed_hash text,
  -- Revealed here, and only here. Until this transaction it was a secret.
  p_server_seed text,
  p_client_seed text,
  -- The commitment for the member's NEXT open, generated by the route and
  -- stored in the same breath as the reveal, so a member is never left without
  -- a live commitment and can never open a chest against a seed they have
  -- already seen.
  p_next_seed text,
  p_next_seed_hash text,
  p_result jsonb,
  p_cards jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entitlement public.chest_entitlements%rowtype;
  v_opening_id uuid;
  v_card jsonb;
  v_retired integer;
begin
  -- Lock the entitlement for the length of the transaction. Two opens racing
  -- on the same chest serialise here, and the second finds it spent.
  select * into v_entitlement
    from public.chest_entitlements
   where id = p_entitlement_id
     and profile_id = p_profile_id
     and opened_at is null
   for update;

  if not found then
    return null;
  end if;

  -- Retire the commitment the roll was made against. If it is no longer active,
  -- another open revealed it first and this roll was computed against a seed
  -- the member may now have seen. Refuse: the route reads the fresh commitment
  -- and rolls again. Nothing has been written at this point, so returning here
  -- leaves no trace.
  update public.chest_seeds
     set active = false,
         revealed_at = now()
   where id = p_seed_id
     and profile_id = p_profile_id
     and active;
  get diagnostics v_retired = row_count;
  if v_retired = 0 then
    return null;
  end if;

  -- Commit the next one immediately. The partial unique index allows exactly
  -- one active commitment per member, which is why this follows the retire
  -- rather than preceding it.
  insert into public.chest_seeds (profile_id, seed, seed_hash, client_seed)
  values (p_profile_id, p_next_seed, p_next_seed_hash, p_client_seed);

  insert into public.chest_openings (
    profile_id, chest_sku, result, server_seed_hash, server_seed, client_seed,
    entitlement_id
  )
  values (
    p_profile_id,
    v_entitlement.chest_sku,
    p_result,
    p_server_seed_hash,
    p_server_seed,
    p_client_seed,
    p_entitlement_id
  )
  returning id into v_opening_id;

  -- The cards, one row per copy, exactly as the holdings ledger stores them.
  -- source_id points back at the opening, so every card in the realm can name
  -- the chest it came out of.
  for v_card in select * from jsonb_array_elements(p_cards)
  loop
    insert into public.inventory (
      profile_id, set_slug, card_number, champion_slug, rarity, source, source_id
    )
    values (
      p_profile_id,
      v_card ->> 'set_slug',
      (v_card ->> 'card_number')::integer,
      v_card ->> 'champion_slug',
      v_card ->> 'rarity',
      'chest_opening',
      v_opening_id
    );
  end loop;

  update public.chest_entitlements
     set opened_at = now(),
         opening_id = v_opening_id
   where id = p_entitlement_id;

  return v_opening_id;
end;
$$;

-- EXECUTE to service_role ONLY. Supabase publishes every public function at
-- /rest/v1/rpc/<name> and the anon key ships in the browser bundle, so a public
-- grant here would let anyone grant themselves cards. See
-- 20260811090000_revoke_public_execute_on_economy_rpcs.sql.
revoke all on function public.chest_open(uuid, uuid, uuid, text, text, text, text, text, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.chest_open(uuid, uuid, uuid, text, text, text, text, text, jsonb, jsonb)
  to service_role;
